token:

engines:
  standard:
    dir: "./engines/"
    name: "stockfish"
    ponder: true
    silence_stderr: false
    move_overhead_multiplier: 1.0
    uci_options:
      Threads: 4
      Hash: 4096
      Move Overhead: 250
    limits:
      # time: 5.0
      # depth: 26
      # nodes: 4000000

  variants:
    dir: "./engines/"
    name: "fairy-stockfish"
    ponder: true
    silence_stderr: false
    move_overhead_multiplier: 1.0
    uci_options:
      Threads: 4
      Hash: 4096
      Move Overhead: 150
      EvalFile: "3check-cb5f517c228b.nnue:antichess-dd3cbe53cd4e.nnue:atomic-2cf13ff256cc.nnue:crazyhouse-8ebf84784ad2.nnue:horde-28173ddccabe.nnue:kingofthehill-978b86d0e6a4.nnue:racingkings-636b95f085e3.nnue"
      Use NNUE: true
    limits:
      time: 5.0

  chess960:
    dir: "./engines/"
    name: "stockfish"
    ponder: true
    silence_stderr: false
    move_overhead_multiplier: 1.0
    uci_options:
      Threads: 7
      Hash: 4096
      Move Overhead: 250
    limits:
      time: 3.0

syzygy:
  standard:
    enabled: true
    paths:
      - "./engines/syzygy"
    max_pieces: 7
    instant_play: true

  antichess:
    enabled: false
    paths:
      - "/path/to/antichess/syzygy"
    max_pieces: 6
    instant_play: true

  atomic:
    enabled: false
    paths:
      - "/path/to/atomic/syzygy"
    max_pieces: 6
    instant_play: true

gaviota:
  enabled: false
  paths:
    - "/path/to/gaviota"
  max_pieces: 5

opening_books:
  enabled: true
  priority: 300
  books:

    standard_white_rated:
      selection: weighted_random
      allow_repetitions: true
      names:
        - white
        - DefaultBook
        - BackupBook
        - Optimus2502
        - Optimus4

    standard_black_rated:
      selection: weighted_random
      allow_repetitions: true
      names:
        - black
        - DefaultBook
        - BackupBook
        - Optimus2502
        - Optimus4

    standard_white_casual:
      selection: weighted_random
      allow_repetitions: true
      names:
        - white
        - Optimus2502
        - Optimus4

    standard_black_casual:
      selection: weighted_random
      allow_repetitions: true
      names:
        - black
        - Optimus2502
        - Optimus4

    standard_white_human:
      selection: weighted_random
      allow_repetitions: true
      names:
        - white

    standard_black_human:
      selection: weighted_random
      allow_repetitions: true
      names:
        - black
        - Optimus2502
        - Optimus4

    standard_white_bot:
      selection: weighted_random
      allow_repetitions: true
      names:
        - white
        - Optimus2502
        - Optimus4

    standard_black_bot:
      selection: weighted_random
      allow_repetitions: true
      names:
        - black

    standard_white_tournament:
      selection: weighted_random
      allow_repetitions: true
      names:
        - white
        - DefaultBook
        - BackupBook

    standard_black_tournament:
      selection: weighted_random
      allow_repetitions: true
      names:
        - black
        - DefaultBook
        - BackupBook

    crazyhouse_white:
      selection: best_move
      names:
        - crazywhite

    crazyhouse_black:
      selection: best_move
      allow_repetitions: true
      names:
        - crazyblack

    kingofthehill_white:
      selection: best_move
      names:
        - kothwhite

    kingofthehill_black:
      selection: best_move
      allow_repetitions: true
      names:
        - kothblack

    antichess_white:
      selection: best_move
      names:
        - antiwhite

    antichess_black:
      selection: best_move
      allow_repetitions: true
      names:
        - antiblack

    threecheck_white:
      selection: best_move
      names:
        - threecheck

    threecheck_black:
      selection: best_move
      allow_repetitions: true
      names:
        - threecheck

    atomic_white:
      selection: best_move
      names:
        - atomic

    atomic_black:
      selection: best_move
      allow_repetitions: true
      names:
        - atomic

    horde_white:
      selection: best_move
      allow_repetitions: true
      names:
        - hordewhite
        - hordenoob

    horde_black:
      selection: best_move
      allow_repetitions: false
      names:
        - hordeblack
        - hordenoob

online_moves:
  opening_explorer:
    enabled: true
    priority: 250
    only_without_book: false
    use_for_variants: false
    allow_repetitions: false
    min_time: 10
    timeout: 5
    min_games: 5
    only_with_wins: false
    selection: "performance"

  lichess_cloud:
    enabled: true
    priority: 250
    only_without_book: false
    use_for_variants: false
    allow_repetitions: false
    trust_eval: false
    min_eval_depth: 30
    min_time: 10
    timeout: 5

  chessdb:
    enabled: true
    priority: 250
    only_without_book: false
    allow_repetitions: false
    trust_eval: false
    min_candidates: 2
    min_time: 10
    timeout: 5
    best_move: true
    selection: "best"

  online_egtb:
    enabled: true
    min_time: 5
    timeout: 2

offer_draw:
  enabled: true
  score: 50
  consecutive_moves: 10
  min_game_length: 35
  against_humans: false
  min_rating: 2900

resign:
  enabled: true
  score: -1000
  consecutive_moves: 10
  against_humans: false
  min_rating: 2900

challenge:
  concurrency: 2
  max_takebacks: 5
  bullet_with_increment_only: false
  variants:
    - standard
    - chess960
    - fromPosition
    - antichess
    - atomic
    - crazyhouse
    - horde
    - kingOfTheHill
    - racingKings
    - threeCheck
  bot_time_controls:
    - bullet
    - blitz
    - rapid
  human_time_controls:
    - bullet
    - blitz
    - rapid
    - classical
  bot_modes:
    - casual
    - rated
  human_modes:
    - casual
    - rated

matchmaking:
  delay: 60
  timeout: 20
  selection: cyclic
  types:
    bullet:
      tc: 0.5+0
      variant: standard
      rated: true
    blitz:
      tc: 3+0
      variant: standard
      rated: true

messages:
  greeting: "Hi! I'm {me} running {engine}. Prepared to get BLOWN UP!!!
  goodbye: "You got BLOWN UP BAD!!! >:D"
  greeting_spectators: "Hi! I'm {me} running {engine}. Watch {opponent} get OBLITERATED >:D"
  goodbye_spectators: "BOOOOOMMMM!!!! Opponent GONE!"

whitelist: []
blacklist: []
online_blacklists: []

books:
  DefaultBook: "./engines/Book2.bin"
  BackupBook: "./engines/Book3.bin"
  Optimus2502: "./engines/OPTIMUS2502.bin"
  Optimus4: "./engines/OPTIMUS4.bin"
  crazywhite: "./engines/crazy_white.bin"
  crazyblack: "./engines/crazy_black.bin"
  kothwhite: "./engines/koth_white.bin"
  kothblack: "./engines/koth_black.bin"
  black: "./engines/std_black.bin"
  white: "./engines/std_white.bin"
  antiwhite: "./engines/whiteanti.bin"
  antiblack: "./engines/blackanti.bin"
  threecheck: "./engines/threecheck_book.bin"
  atomic: "./engines/atomic.bin"
  horde: "./engines/horde.bin"
  hordeblack: "./engines/black_horde.bin"
  hordenoob: "./engines/horde.bin"
  hordewhite: "./engines/horde_best.bin"
