name: Upload Lichess Status Snapshot

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  upload-status:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Lichess bot repo
        uses: actions/checkout@v4

      - name: Upload status artifact
        uses: actions/upload-artifact@v4
        with:
          name: lichess-status
          path: lichess_status.json
          if-no-files-found: ignore  

      - name: Trigger Discord repo workflow
        run: |
          echo "Triggering Discord workflow..."
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/Omo-star/absolute-horsey-bott/dispatches \
            -d '{"event_type": "download-lichess-status"}'
